### ISSUE TITLE
Error after install via composer

### ISSUE THREAD

**Issue by Rocker506** [c006/yii2-auto-crud#3]
![captura de pantalla 2016-02-12 a las 1 48 20](https://cloud.githubusercontent.com/assets/3498987/13001370/c5b3a580-d12a-11e5-9f4f-7e1a169f03db.png)

I recently installed the extension, but I can not use it because this error, any idea what I'm doing wrong, I installed through composer, and try to install it manually by downloading the repository.

Thanks for your hard work.

**Comment by Rocker506** [comment]
By the way, I'm using Yii 2.0.6 with Php 5.6.10, over a MAMP dev server.

**Comment by Rocker506** [comment]
I got it. 

Sorry, you forgot to write this line in the section: **"Install before using yii2-auto-crud"**

`php composer.phar require --prefer-source "c006/yii2-core" "dev-master"`

**Comment by c006** [comment]
Hi.

I will update yii2-auto-crud to so it adds it automatically.
Thank you for the information.

Regards,
Jon
